services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    command: ["/entrypoint.sh"]
    networks:
      - app-network
    volumes:
      - .:/app

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_db
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file: .env
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge