services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:8000

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    command: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - db
      - redis
    networks:
      - default

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_db
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file: .env
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge