"""Initial schema setup

Revision ID: d670c96ff01e
Revises:
Create Date: 2025-08-01 15:55:07.434899

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d670c96ff01e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_app_users"),
    )
    op.create_index(
        "ix_app_users_username", "app_users", ["username"], unique=True
    )
    op.create_table(
        "resume_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=True),
        sa.Column("analysis_results", sa.JSON(), nullable=True),
        sa.Column("optimized_resume", sa.Text(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("overall_rating", sa.String(length=50), nullable=True),
        sa.Column("missing_keywords_count", sa.Integer(), nullable=True),
        sa.Column("improvements_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_users.id"], name="fk_resume_analyses_user_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_resume_analyses"),
    )
    op.create_index(
        op.f("ix_resume_analyses_session_id"),
        "resume_analyses",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_resume_analyses_user_id",
        "resume_analyses",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_resume_analyses_user_id", table_name="resume_analyses")
    op.drop_index(
        op.f("ix_resume_analyses_session_id"), table_name="resume_analyses"
    )
    op.drop_table("resume_analyses")
    op.drop_index("ix_app_users_username", table_name="app_users")
    op.drop_table("app_users")
    # ### end Alembic commands ###
