# .streamlit/config.toml

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
runOnSave = false
enableStaticServing = true

[theme]
# Colors
primaryColor = "#cb785c"
backgroundColor = "#fdfdf8"
secondaryBackgroundColor = "#f0f0ec"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"

# Borders and Radius
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full" # This makes buttons pill-shaped

# Typography
# These font family names MUST EXACTLY MATCH the names provided by Google Fonts.
font = "Space Grotesk"
headingFontWeights = [700, 600, 600, 600, 600, 600]
headingFontSizes = ["2.5rem", "2rem", "1.75rem", "1.5rem", "1.25rem", "1.1rem"]
codeFont = "Space Mono"
codeFontSize = "0.85rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = false

# Charts
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24", "#ef4444", "#a855f7"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"
baseRadius = "0.75rem"