[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "https://fonts.gstatic.com/s/spacegrotesk/v16/V8mQoQDjQSkFtoMM3T6r8E7GUBFBs0FZIpFSqPE.woff2"

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "https://fonts.gstatic.com/s/spacegrotesk/v16/V8mDoQDjQSkFtoMM3T6r8E7GUBJFKpOXLNGFw4OD.woff2"
weight = 600

[[theme.fontFaces]]
family = "SpaceMono"
url = "https://fonts.gstatic.com/s/spacemono/v13/i7dPIFZifjKcF5UAWdDRYEF8RXi4EwSs.woff2"
style = "normal"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "https://fonts.gstatic.com/s/spacemono/v13/i7dMIFZifjKcF5UAWdDRaPpZYFKp.woff2"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "https://fonts.gstatic.com/s/spacemono/v13/i7dNIFZifjKcF5UAWdDRYER8QHi-Ew.woff2"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "https://fonts.gstatic.com/s/spacemono/v13/i7dSIFZifjKcF5UAWdDRYEREWFAyQ3g.woff2"
style = "italic"
weight = 700